rest:
  auth-open: false #jwt鉴权机制是否开启(true或者false)
  sign-open: false #签名机制是否开启(true或false)

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: randomKey      #md5加密混淆key

filter:
  origin:
    url: http://localhost:8080  #前后端跨域配置,允许跨域地址,手工承保必须配置
    open: false #是否打开跨域配置

server:
  port: 18003 #项目端口
#  context-path: /mit
mybatis-plus:
  mapper-locations: classpath*:com/cmft/mit/**/mapping/*.xml
  typeAliasesPackage: com.cmft.mit.order.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

spring:
  datasource:
      url: jdbc:mysql://10.12.12.64:3306/mit?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: mysql
      filters: log4j,wall,mergeStat

  redis:
      host: 10.12.12.64
      port: 6379
      password: redis
      database: 4
      timeout: 0
      pool:
        max-idle: 20
        min-idle: 8
        max-wait: -1
  rabbitmq:
      host: ${RABBIT_MQ_HOST:10.1.32.162}
      port:  ${RABBIT_MQ_PORT:5672}
      username: admin
      password: 111111
  zipkin:
      enabled: true
  sleuth:
      sampler:
        percentage: 1
        
enanbleScan: Y    #是否启动定时扫描订单，Y为是，N为否  
scanFrequency: 30  #扫描频率，单位：分钟
invaliadTime: 1440   #失效时间，单位：分钟

enanbleSyn: N    #是否启动定时同步客户数据，Y为是，N为否
synFrequency: 120  #同步客户数据频率（xx分钟同步一次），单位：分钟

test: kkkkeeeeeeeeeeeeeeeeeeeeeeeeeekkkkk

 